name: add-from-issue

on:
  issues:
    types: [labeled]

jobs:
  add-item:
    if: github.event.label.name == 'new addition'
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: npm

      - name: Install
        run: npm ci

      # - name: Print Test 
      #   run: echo "body-> ${{ github.event.issue.body }} event."

      - name: Create branch
        run: git checkout -b ${{github.event.issue.title}}

      - name: Add from body of issue
        run: npm run add-from-issue $'${{ github.event.issue.body }}'

      - name: Commit group update
        run: git add groups.ts && git commit -m "Added from issue '${{github.event.issue.title}}'" && git push origin ${{github.event.issue.title}}

      - name: create pull request
        run: gh pr create -B main -H ${{github.event.issue.title}} --title 'Merge ${{github.event.issue.title}} into main' --body 'closes ${{github.event.issue.number}}'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
