name: add-from-issue

on:
  issues:
    types: [labeled]

jobs:
  add-item:
    if: github.event.label.name == 'new addition'
    permissions:
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: npm

      - name: Install
        run: npm ci

      - name: Print Test 
        uses: actions/github-script@v1
        with:
          script: |
            console.log('${{ github.event.issue.body }}')

      # - name: Commit
      #   uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     add_options: "--force README.md UP.md CLOSED.md"
      #     commit_message: Generate READMEs
